package com.marriageonmind.model.marriage.occupation;

public enum ShopCategory {
JEWELLERY,CLOTH,GROCERY,MEDICINE,PAINT,STATIONERY,PRINTINGPRESS,TRAINING,VEGETABLE,
ELECTRICGOODS,ELECTRONICS,HOTEL,RESTAURANT,PHOTOSTUDIO,CONSTRUCTION
}
