package com.marriageonmind.model.advertiser;

public enum ShopCategory {
GROCERY,MEDICINE,PAINT,STATIONERY,PRINTINGPRESS,TRAINING,VEGETABLE,
ELECTRICGOODS,ELECTRONICS,HOTEL,RESTAURANT,PHOTOSTUDIO,CONSTRUCTION
}
