package com.marriageonmind.persistence.model;

public enum ShopCategory {
JEWELLERY,CLOTH,GROCERY,MEDICINE,PAINT,STATIONERY,PRINTINGPRESS,TRAINING,VEGETABLE,
ELECTRICGOODS,ELECTRONICS,HOTEL,RESTAURANT,PHOTOSTUDIO,CONSTRUCTION
}
