package com.marriageonmind.model.marriage;

public enum Profession {
MANAGER,DOCTOR,ENGINEER,TEACHER,BANKCLERK,BANKPO,BANKOFFICER,BUSINESS,GOVTJOB,SOFTWAREENGINEER,SENIORSOFTWAREENGINEER,SCIENTIST
}
